#pragma once

namespace ee0
{

enum MessageID
{
	MSG_INSERT_SCENE_NODE = 0,
	MSG_DELETE_SCENE_NODE,
	MSG_CLEAR_SCENE_NODE,
	MSG_REORDER_SCENE_NODE,

	MSG_NODE_SELECTION_INSERT,
	MSG_NODE_SELECTION_DELETE,
	MSG_NODE_SELECTION_CLEAR,
	
	MSG_SET_CANVAS_DIRTY,
	MSG_SET_EDITOR_DIRTY,

	MSG_UPDATE_COMPONENTS,
	MSG_STAGE_PAGE_CHANGING,
	MSG_STAGE_PAGE_CHANGED,
	MSG_STAGE_PAGE_ON_SHOW,
};

}