#pragma once

namespace ee0
{

enum MessageID
{
	MSG_SCENE_NODE_INSERT = 0,
	MSG_SCENE_NODE_DELETE,
	MSG_SCENE_NODE_CLEAR,
	MSG_SCENE_NODE_UP_DOWN,
    MSG_SCENE_NODE_SWAP,

	MSG_NODE_SELECTION_INSERT,
	MSG_NODE_SELECTION_DELETE,
	MSG_NODE_SELECTION_CLEAR,

	MSG_SET_CANVAS_DIRTY,
	MSG_SET_EDITOR_DIRTY,
	MSG_EDITOR_RELOAD,

	MSG_UPDATE_COMPONENTS,
	MSG_UPDATE_NODES,

    MSG_STAGE_PAGE_NEW,
	MSG_STAGE_PAGE_CHANGING,
	MSG_STAGE_PAGE_CHANGED,
	MSG_STAGE_PAGE_ON_SHOW,
	MSG_STAGE_PAGE_ON_HIDE,

	MSG_UPDATE_NODE_NAME,

	MSG_ATOMIC_OP_ADD,
	MSG_EDIT_OP_UNDO,
	MSG_EDIT_OP_REDO,
};

}